language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_c838854b6b9b_key -iv $encrypted_c838854b6b9b_iv
  -in tencent-rsa.enc -out ~\/.ssh/tencent-rsa -d
- chmod 600 ~/.ssh/tencent-rsa # 改变文件权限
- eval $(ssh-agent) # 配置 ssh
- ssh-add ~/.ssh/tencent-rsa
- cp .travis/ssh_config  ~/.ssh/config

install:
- npm install
script:
- npm run sync:generate
after_script:
- cd ./public
- git init
- git config --local user.name "nanzaichen"
- git config --local user.email "zuixuanminzufeng@163.com"
- git add .
- git commit -m "Update By TravisCI With Build $TRAVIS_BUILD_NUMBER"
- git push --force --quiet "git@git.dev.tencent.com:nanzaichen/xiaopingziblog.git" master:master
branches:
  only:
  - master
# 缓存node_modules 节约时间
cache:
  directories:
  - node_modules
